EXTERN _memset

EXTERN _PrintHexB@4,_PrintHexD@4, _PrintStr@4
;EXTERN _HexToStr32@8
EXTERN _Hex32ToStr@16
EXTERN _PrintChar@4,_SetDefaultOutput@4

EXTERN  __mul64,__div64

EXTERN _SchedulerX@4, _SchedulerCX@0
EXTERN _GetCurrentEXU@0
EXTERN _GetCurrentThread@0
EXTERN _GetThreadName@8
EXTERN _TimerHandler@0

EXTERN _GetDebugThreadX@0
EXTERN _SetDebugThreadX@4

EXTERN _printf

EXTERN _DebugProcess@8
EXTERN _KernelEntry@20
