objconv -felf32 add64.obj
objconv -felf32 chkstk.obj
objconv -felf32 div64.obj
objconv -felf32 memccpy.obj
objconv -felf32 memchr.obj
objconv -felf32 memcmp.obj
objconv -felf32 memcpy.obj
objconv -felf32 memcpyx.obj
objconv -felf32 memdiff.obj
objconv -felf32 memmov32.obj
objconv -felf32 memmove.obj
objconv -felf32 mempcpy.obj
objconv -felf32 memrchr.obj
objconv -felf32 memset.obj
objconv -felf32 mul64.obj
objconv -felf32 rawmemch.obj
objconv -felf32 setjmp.obj
objconv -felf32 strcat.obj
objconv -felf32 strchrnl.obj
objconv -felf32 strchr.obj
objconv -felf32 strcmp.obj
objconv -felf32 strcpy.obj
objconv -felf32 strlen.obj
objconv -felf32 strncat.obj
objconv -felf32 strncmp.obj
objconv -felf32 strncpy.obj
objconv -felf32 strnlen.obj
objconv -felf32 strrchr.obj
objconv -felf32 strstr.obj
objconv -felf32 sub64.obj
objconv -felf32 wcschrnl.obj
objconv -felf32 wcschr.obj
objconv -felf32 wcscmp.obj
objconv -felf32 wcscpy.obj
objconv -felf32 wcslen.obj
objconv -felf32 wcsncmp.obj
objconv -felf32 wcsstr.obj
objconv -felf32 wmemchr.obj
objconv -felf32 wmemcpy.obj
objconv -felf32 wmempcpy.obj
objconv -felf32 wmemrchr.obj
objconv -felf32 wmemset.obj
objconv -felf32 xmemdiff.obj
